// Generated by Selenium IDE

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SecondTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void second() {
    driver.get("https://login.salesforce.com/");
    driver.manage().window().setSize(new Dimension(1680, 985));
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).click();
    {
      final WebElement element = driver.findElement(By.id("username"));
      final Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).click();
    {
      final WebElement element = driver.findElement(By.id("username"));
      final Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("main")).click();
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).click();
    {
      final WebElement element = driver.findElement(By.id("password"));
      final Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("Login")).click();
    driver.findElement(By.linkText("Opportunities")).click();
    driver.findElement(By.name("new")).click();
    driver.findElement(By.id("opp3")).click();
    driver.findElement(By.id("opp3")).sendKeys("secondoppcreation");
    driver.findElement(By.id("opp9")).click();
    driver.findElement(By.linkText("3/4/2020")).click();
    driver.findElement(By.id("opp9")).sendKeys("3/4/2020");
    driver.findElement(By.linkText("3/4/2020")).click();
    driver.findElement(By.linkText("3/4/2020")).click();
    driver.findElement(By.id("opp11")).click();
    {
      final WebElement dropdown = driver.findElement(By.id("opp11"));
      dropdown.findElement(By.xpath("//option[. = 'Qualification']")).click();
    }
    driver.findElement(By.id("opp5")).click();
    {
      final WebElement dropdown = driver.findElement(By.id("opp5"));
      dropdown.findElement(By.xpath("//option[. = 'New Customer']")).click();
    }
    driver.findElement(By.id("opp6")).click();
    {
      final WebElement dropdown = driver.findElement(By.id("opp6"));
      dropdown.findElement(By.xpath("//option[. = 'Web']")).click();
    }
    driver.findElement(By.id("00N4T000002SQmp")).click();
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.id("00N4T000002SQmp")).sendKeys("cisco");
    driver.findElement(By.id("head_2_ep")).click();
    {
      final WebElement element = driver.findElement(By.id("opp14"));
      final Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("opp14")).click();
  
      final WebElement element = driver.findElement(By.tagName("body"));
      final Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("opp14")).sendKeys("test");
    driver.findElement(By.cssSelector("#bottomButtonRow > .btn:nth-child(1)")).click();
  }
}
